# Generated by Django 4.2.6 on 2023-10-10 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='description',
            new_name='message',
        ),
    ]
