# Generated by Django 4.2.6 on 2023-10-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amdCPU',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wattage', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='amdMotherboard',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wattage', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wattage', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='cooler',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wattage', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='gpu',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wattage', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='intelCPU',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wattage', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='intelMotherboard',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wattage', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='psu',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wattage', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ram',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wattage', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wattage', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/images/')),
            ],
        ),
    ]
